simple_map_publisher:
  ros__parameters:
    map_width: 100
    map_height: 100
    resolution: 0.05
    origin_x: -2.5
    origin_y: -2.5
    publish_rate: 1.0
    wall_obstacles: true
    obstacles: [1.0, 0.0, 0.5, -1.0, 1.0, 0.4, 0.5, -1.5, 0.3]
    inflation_radius_cells: 3
